name: Documenter
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: nightly
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
